# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Engineering/projekt_sdup/projekt_sdup.srcs/sources_1/bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_1/audio_AXI_DMA_xbar_1.xci
# IP: The module: 'audio_AXI_DMA_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Engineering/projekt_sdup/projekt_sdup.gen/sources_1/bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_1/audio_AXI_DMA_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_AXI_DMA_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Engineering/projekt_sdup/projekt_sdup.srcs/sources_1/bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_1/audio_AXI_DMA_xbar_1.xci
# IP: The module: 'audio_AXI_DMA_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Engineering/projekt_sdup/projekt_sdup.gen/sources_1/bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_1/audio_AXI_DMA_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_AXI_DMA_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
