# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/design_AdjustCoeffsAXI/design_AdjustCoeffsAXI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI || ORIG_REF_NAME==design_AdjustCoeffsAXI} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_myip_v1_0_S00_AXI_0_1/design_AdjustCoeffsAXI_myip_v1_0_S00_AXI_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_myip_v1_0_S00_AXI_0_1 || ORIG_REF_NAME==design_AdjustCoeffsAXI_myip_v1_0_S00_AXI_0_1} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_clk_wiz_0_1/design_AdjustCoeffsAXI_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_clk_wiz_0_1 || ORIG_REF_NAME==design_AdjustCoeffsAXI_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_processing_system7_0_1/design_AdjustCoeffsAXI_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_processing_system7_0_1 || ORIG_REF_NAME==design_AdjustCoeffsAXI_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_ps7_0_axi_periph_0/design_AdjustCoeffsAXI_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_AdjustCoeffsAXI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_rst_clk_wiz_0_25M_0/design_AdjustCoeffsAXI_rst_clk_wiz_0_25M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_AdjustCoeffsAXI_rst_clk_wiz_0_25M_0} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_rst_ps7_0_100M_0/design_AdjustCoeffsAXI_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_AdjustCoeffsAXI_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_auto_cc_0/design_AdjustCoeffsAXI_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_auto_cc_0 || ORIG_REF_NAME==design_AdjustCoeffsAXI_auto_cc_0} -quiet] -quiet

# IP: bd/design_AdjustCoeffsAXI/ip/design_AdjustCoeffsAXI_auto_pc_0/design_AdjustCoeffsAXI_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_AdjustCoeffsAXI_auto_pc_0 || ORIG_REF_NAME==design_AdjustCoeffsAXI_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Engineering/projekt_sdup/projekt_sdup.gen/sources_1/bd/design_AdjustCoeffsAXI/design_AdjustCoeffsAXI_ooc.xdc
