# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/audio_AXI_DMA/audio_AXI_DMA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA || ORIG_REF_NAME==audio_AXI_DMA} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_audio_axis_tx_0_0/audio_AXI_DMA_audio_axis_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_audio_axis_tx_0_0 || ORIG_REF_NAME==audio_AXI_DMA_audio_axis_tx_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_audio_axis_tx_1_0/audio_AXI_DMA_audio_axis_tx_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_audio_axis_tx_1_0 || ORIG_REF_NAME==audio_AXI_DMA_audio_axis_tx_1_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_clk_wiz_0_0/audio_AXI_DMA_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_clk_wiz_0_0 || ORIG_REF_NAME==audio_AXI_DMA_clk_wiz_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_processing_system7_0_0/audio_AXI_DMA_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_processing_system7_0_0 || ORIG_REF_NAME==audio_AXI_DMA_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_0/audio_AXI_DMA_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_xbar_0 || ORIG_REF_NAME==audio_AXI_DMA_xbar_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_ps7_0_axi_periph_0/audio_AXI_DMA_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_AXI_DMA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_rst_ps7_0_100M_0/audio_AXI_DMA_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_rst_ps7_0_100M_0 || ORIG_REF_NAME==audio_AXI_DMA_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_proc_sys_reset_0_0/audio_AXI_DMA_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_proc_sys_reset_0_0 || ORIG_REF_NAME==audio_AXI_DMA_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_axi_dma_0_0/audio_AXI_DMA_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_axi_dma_0_0 || ORIG_REF_NAME==audio_AXI_DMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_axis_data_fifo_0_0/audio_AXI_DMA_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_axis_data_fifo_0_0 || ORIG_REF_NAME==audio_AXI_DMA_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_axis_data_fifo_0_2/audio_AXI_DMA_axis_data_fifo_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_axis_data_fifo_0_2 || ORIG_REF_NAME==audio_AXI_DMA_axis_data_fifo_0_2} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_axi_dma_0_2/audio_AXI_DMA_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_axi_dma_0_2 || ORIG_REF_NAME==audio_AXI_DMA_axi_dma_0_2} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_xbar_1/audio_AXI_DMA_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_xbar_1 || ORIG_REF_NAME==audio_AXI_DMA_xbar_1} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_axi_interconnect_0_0/audio_AXI_DMA_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_axi_interconnect_0_0 || ORIG_REF_NAME==audio_AXI_DMA_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_AudioSystem_AXI_wrap_0_0/audio_AXI_DMA_AudioSystem_AXI_wrap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_AudioSystem_AXI_wrap_0_0 || ORIG_REF_NAME==audio_AXI_DMA_AudioSystem_AXI_wrap_0_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_auto_pc_0/audio_AXI_DMA_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_auto_pc_0 || ORIG_REF_NAME==audio_AXI_DMA_auto_pc_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_auto_cc_0/audio_AXI_DMA_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_auto_cc_0 || ORIG_REF_NAME==audio_AXI_DMA_auto_cc_0} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_auto_pc_1/audio_AXI_DMA_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_auto_pc_1 || ORIG_REF_NAME==audio_AXI_DMA_auto_pc_1} -quiet] -quiet

# IP: bd/audio_AXI_DMA/ip/audio_AXI_DMA_auto_pc_2/audio_AXI_DMA_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_AXI_DMA_auto_pc_2 || ORIG_REF_NAME==audio_AXI_DMA_auto_pc_2} -quiet] -quiet

# XDC: c:/Users/Engineering/projekt_sdup/projekt_sdup.gen/sources_1/bd/audio_AXI_DMA/audio_AXI_DMA_ooc.xdc
